[tool.poetry]
name = "oai-assistant"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.332,<0.1.0"
openai = ">1,<2"
langchain-experimental = "^0.0.38"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "oai_assistant"
export_attr = "agent_executor"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
