---
name: Publish Package to PyPi

on:
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    permissions: write-all
    with:
      working-directory: .
    secrets: inherit
